### ISSUE TITLE
How to inform community about known breakages

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/NG#31]
How can we do a better job at this?

**Comment by yoshuawuyts** [comment]
This is for new bugs popping up right? (e.g. to be fixed)

Perhaps something like status.github.io but for Node could work - list the latest releases / LTS versions and known bugs / failures. Could come in handy for linking back to from tweets and stuff - I reckon it might be better on the eyes than linking to GitHub issues. What do you reckon?

**Comment by rvagg** [comment]
that could be pretty easily achieved with labels, and our collaborator army is pretty awesome with applying labels

**Comment by thefourtheye** [comment]
semver-major tag should be a good indicator, no?

**Comment by mikeal** [comment]
This should probably go on the `roadmap` or `evangelism` repo depending on how you see it playing out. This is something that is actionable _today_ so it doesn't need to be in NG.
