### ISSUE TITLE
Requested GitHub implement 'Author Only' labels...

### ISSUE THREAD

**Issue by ghost** [nodejs/NG#32]
...to let community help organize issues and PRs

Sent to support@github.com

> Owners of highly visible repos, like nodejs, receive tons of issues and PRs. 
> 
> They often need to organize them by assigning labels, and then manage their workflow by assigning additional lifecycle labels. 
> 
> Only repo members can create and assign labels, and this is a good thing.
> 
> However, the author of the item often does know if it's of a certain class or kind, such as 'experimental' or 'RFP', usually a handful of others.
> 
> It would be incredibly useful if a repo owner could define **'Author Only'** labels that were separate from the **'Member Only'** labels (labels as they currently function).
> 
> **'Author Only'** labels could be assigned only by the author of an issue or PR.
> 
> This would greatly improve the overall organization of items, as it wouldn't require repo members to review every single item just to categorize it for organizational reasons, and allow authors to specify they're intended classification, rather than what a members interpretation might be.
> 
> For example, `nodeJjs` created an `NG` repo just to segregate issues from the `node` repo, that are more of a research nature.
> 
> `nodejs` also created a `node-eps` repo, just to segregate proposals offered by people who could implement them, but locked issue creation specifically to minimize noise; eps's must be submitted as actual files, meaning forks and PRs just to submit a file.
> 
> Unfortunately, these separate repos, being separate, go unnoticed because all activity with node happens in the node repo.
> 
> If github was open source, I would myself implement this immediately.

**Comment by ghost** [comment]
It appears this repo is a ghost town. Closing this issue.

**Comment by Jeff-Lewis** [comment]
Maybe more appropriate here https://github.com/isaacs/github
